services:
  backend:
    env_file: .env
    build: ./backend/
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend/
    ports:
      - "80:3000"
    environment:
      - WDS_SOCKET_PORT=0